spring:
  datasource:
     url: jdbc:mysql://localhost:3306/e_rank?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
     username: root
     password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      use_sql_comments: true
      format_sql: true
        storage_engine:innodb
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 763158131226-k4926josgdecm7o6gcfscbq5v8vib65e.apps.googleusercontent.com
            client-secret: vyz-gahvlomwSJGDHizQdHlY
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
             - email
             - profile
          facebook:
            client-id: 1038423279912140
            client-secret: 37100a38fca41027583d8f3f467e5671
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}" # Note that facebook now mandates the use of https redirect URIs, so make sure your app supports https in production
            scope:
             - email
             - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    token-secret: 926D96C90030DD58429D2751AC1BDBBC
    token-expiration-msec: 864000000
  oauth2:
  # After successfully authenticating with the OAuth2 Provider,
  # we'll be generating an auth token for the user and sending the token to the
  # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
  # We're not using cookies because they won't work well in mobile clients.
    authorized-redirect-uris:
    - http://localhost:3000/oauth2/redirect
    - myandroidapp://oauth2/redirect
    - myiosapp://oauth2/redirect
    
logging:
  level:
    org:
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE