spring:
  datasource:
     url: jdbc:mysql://localhost:3306/e_rank?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
     username: root
     password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      use_sql_comments: true
      format_sql: true
        storage_engine:innodb
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true